### ISSUE TITLE
[Bug] extension_f5_tts: "Unload Model" does not work

### ISSUE THREAD

**Issue by admdev24** [rsxdalv/extension_f5_tts#3]
https://github.com/rsxdalv/extension_f5_tts/blob/47a375f08e980060c7e0f13e3e690463f6787ffc/extension_f5_tts/gradio_app.py#L375

"Unload Model" does not unload the model off the VRAM. 

To verify:

`nvidia-smi`

**Comment by rsxdalv** [comment]
Great find! Should be fixed in #[460112d](https://github.com/rsxdalv/extension_f5_tts/commit/460112ddfa63067b805df43a0f1fd1d7c9b1caf8)

Changed 
            unload_model_button("tts_model")
to             unload_model_button("f5_tts_model")

**Comment by rsxdalv** [comment]
If you see any other issue, please comment here, for now I will close this.

**Comment by admdev24** [comment]
I have tested your new update on both F5/E2 Models;
I'm afraid changing the model name to "f5_tts_model" did not fix the unload issue, that was actually the first thing I thought about!
Do you think this might be a model related issue not the logic behind the unload method?
